services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb'
    image: 'amazon/dynamodb-local:latest'
    ports:
      - '8000:8000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi',
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - edb
  node:
    image: node:20-alpine
    working_dir: /home/node
    volumes:
      - .:/home/node
    command: 'node index.js'
    depends_on:
      dynamodb-local:
        condition: service_healthy
    tty: true
    networks:
      - edb

networks:
  edb:
    driver: bridge
